/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Calendar;
import java.util.GregorianCalendar;
import back.Battle;
import back.Schedule;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Isabelle
 */
public class AddOrEditBattleFrame extends javax.swing.JFrame {

    private static Battle FIGHT;
    private static boolean EDIT;
    private static GregorianCalendar DATE;
    public AddOrEditBattleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstOpponentField = new javax.swing.JTextField();
        secondOpponentField = new javax.swing.JTextField();
        vsLabel = new javax.swing.JLabel();
        bracketCombo = new javax.swing.JComboBox<>();
        timeCombo = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        vsLabel.setFont(vsLabel.getFont().deriveFont(vsLabel.getFont().getSize()-2f));
        vsLabel.setText("vs");

        bracketCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UBER", "OU", "UU", "RU", "NU" }));

        submitButton.setText("submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        infoLabel.setText("Opponent one:          Opponent two:           Bracket:                    Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstOpponentField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(vsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondOpponentField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bracketCombo, 0, 80, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(timeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstOpponentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsLabel)
                    .addComponent(bracketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondOpponentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String name1 = firstOpponentField.getText();
        String name2 = secondOpponentField.getText();
        if(name1.equals("") || name2.equals(""))
            JOptionPane.showMessageDialog(null, "Must enter name.", "ERROR", JOptionPane.ERROR_MESSAGE);
        else
        {
            int b = bracketCombo.getSelectedIndex();
            String bracket = bracketCombo.getItemAt(b);
            int t = timeCombo.getSelectedIndex();
            String time = timeCombo.getItemAt(t);
            AddOrEditBattleFrame.makeDateFromTime(time);
            Battle make = new Battle(name1, name2, bracket, DATE);
            if(EDIT)
            {
                AddOrEditBattleFrame.editBattle(make);
            }
            else
            {
                AddOrEditBattleFrame.addToSchedule(make);
            }
            ScheduleFrame.setBattleList(DATE);
        }
        this.setVisible(false);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrEditBattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrEditBattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrEditBattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrEditBattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrEditBattleFrame().setVisible(true);
            }
        });
    }
    
    public static void setVariables(Battle f, boolean e, GregorianCalendar d)
    {
        FIGHT = f;
        EDIT = e;
        DATE = d;
        AddOrEditBattleFrame.fillTime();
    }
    
    private static void fillTime()
    {
        int hours = 24*2;
        GregorianCalendar fill = new GregorianCalendar(DATE.get(Calendar.YEAR), 
                                                       DATE.get(Calendar.MONTH), 
                                                       DATE.get(Calendar.DAY_OF_MONTH), 
                                                       0,0);
        String add = "";
        SimpleDateFormat fmt = new SimpleDateFormat("HH:mm");
        for(int i = 0; i < hours; i++)
        {
            add = fmt.format(fill.getTime());
            timeCombo.addItem(add);
            fill.add(Calendar.MINUTE, 30);
        }
    }
    
    private static void addToSchedule(Battle fight)
    {
        Schedule sched = new Schedule();
        if(sched.loadScheduleFromStorageFile())
        {
           if(sched.addToSchedule(fight))
           {
               sched.writeScheduleToStorageFile();
           }
        }
    }
    
    private static void editBattle(Battle edit)
    {
        Schedule sched = new Schedule();
        if(sched.loadScheduleFromStorageFile())
        {
           if(sched.updateBattleInSchedule(FIGHT, edit))
           {
               sched.writeScheduleToStorageFile();
           }
        }
    }
    
    private static void makeDateFromTime(String time)
    {
        String sep = ":";
        String[] newTime = new String[2];
        newTime = time.split(sep);
        int hour = Integer.parseInt(newTime[0]);
        int min = Integer.parseInt(newTime[1]);
        
        DATE = new GregorianCalendar(DATE.get(Calendar.YEAR), 
                                     DATE.get(Calendar.MONTH), 
                                     DATE.get(Calendar.DAY_OF_MONTH), 
                                     hour,min);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> bracketCombo;
    private static javax.swing.JTextField firstOpponentField;
    private javax.swing.JLabel infoLabel;
    private static javax.swing.JTextField secondOpponentField;
    private javax.swing.JButton submitButton;
    private static javax.swing.JComboBox<String> timeCombo;
    private javax.swing.JLabel vsLabel;
    // End of variables declaration//GEN-END:variables
}
